### ISSUE TITLE
.env.example file is missing

### ISSUE THREAD

**Issue by victorantos** [veyabidlek/jazba-ai#3]
[README.md](https://github.com/veyabidlek/jazba-ai/blob/main/README.md) file mentions a non existing file [.env.example](https://github.com/veyabidlek/jazba-ai/blob/main/.env.example)

**Comment by victorantos** [comment]
Shall we just add a .env.example file to the server and client folders?

```
# Your API Key for GEMINI_API
GEMINI_API_KEY=
```

**Comment by veyabidlek** [comment]
Yes, thank you. I think I have somehow accidentally deleted it or something.
I added it now.
